### PR TITLE
Random mode option for each single starting point.

### PR DESCRIPTION
**Pull request by pikachunakapika**
Hi brichard.
Thank you for BitCrack!
Maybe you are interested to have this option in upstream too.

Best Regards

### CODE REVIEW

**Comment by pikachunakapika** [comment]
Closing for some restructuring.

**Comment by bill32767** [comment]
Please how can I use the Random option? I tried using this
option cuBitCrack -r -d 1 -b 48 -t 256 -p 1120
1AVJKwzs9AskraJLGHAZPiaZcrpDr1U6AB --continue d.txt -o 1M.txt and it says
"r is an invalid address" please help with settings. Thanks.

**Comment by pikachunakapika** [comment]
Hi,

please get binaries from here for now:

https://github.com/ZielarSRC/BitCrack/releases

**Comment by bill32767** [comment]
Thanks but I have done it and it gives this error:  rror] Error detecting
devices: CUDA driver version is insufficient for CUDA runtime version

Please where to place Cudart32&64 files?

The above error happens anytime I run the Bitcrack 3.0 and the latest CUDA
Driver wouldn't install (always saying system restart is required).

**Comment by RastaDollo** [comment]
which old version supports -r ?

**Comment by thearthouse** [comment]
> Hi,
> 
> please get binaries from here for now:
> 
> https://github.com/ZielarSRC/BitCrack/releases

hi pikachunakapika . after generateStartingPoints how it is generates next random key from _stepKernel i cant find that code/file ? can you refer

**Pull request closed without merging**
